---
- name: Instalar e configurar o Zabbix Agent em sistemas Red Hat-based
  hosts: all
  become: yes  # Executa como superusuário (sudo)
  tasks:
    - name: Adicionar repositório Zabbix para Red Hat
      yum_repository:
        name: zabbix
        description: Zabbix Official Repository
        baseurl: https://repo.zabbix.com/zabbix/6.4/rhel/{{ ansible_distribution_major_version }}/x86_64/
        gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
        gpgcheck: yes
        enabled: yes

    - name: Instalar o Zabbix Agent
      yum:
        name: zabbix-agent
        state: present

    - name: Configurar o arquivo do Zabbix Agent
      template:
        src: zabbix_agentd.conf.template
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: zabbix
        group: zabbix
        mode: '0644'
      notify:
        - Reiniciar Zabbix Agent

    - name: Habilitar e iniciar o serviço do Zabbix Agent
      service:
        name: zabbix-agent
        enabled: yes
        state: started

  handlers:
    - name: Reiniciar Zabbix Agent
      service:
        name: zabbix-agent
        state: restarted