---
- name: Instalar e configurar o Zabbix Agent em sistemas Ubuntu-based
  hosts: all
  become: yes  # Executa como superusuário (sudo)
  tasks:
    - name: Adicionar repositório Zabbix para Ubuntu
      apt_repository:
        repo: "deb https://repo.zabbix.com/zabbix/6.4/ubuntu/ {{ ansible_distribution_release }} main"
        state: present
        filename: zabbix
        update_cache: yes
        keyserver: hkp://keyserver.ubuntu.com:80
        key: 082AB56BA14FE591

    - name: Instalar o Zabbix Agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: yes

    - name: Configurar o arquivo do Zabbix Agent
      template:
        src: zabbix_agentd.conf.template
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: zabbix
        group: zabbix
        mode: '0644'
      notify:
        - Reiniciar Zabbix Agent

    - name: Habilitar e iniciar o serviço do Zabbix Agent
      service:
        name: zabbix-agent
        enabled: yes
        state: started

  handlers:
    - name: Reiniciar Zabbix Agent
      service:
        name: zabbix-agent
        state: restarted